"""empty message

Revision ID: b001096368a7
Revises: 6d900dc8204b
Create Date: 2020-03-21 19:47:57.428252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b001096368a7'
down_revision = '6d900dc8204b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'count')
    # ### end Alembic commands ###
